apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitoring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-monitoring-app
  template:
    metadata:
      labels:
        app: redis-monitoring-app
    spec:
      containers:
      - name: redis-monitoring-app
        image: conqrean/redis-monitoring-app:v0.3
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "172.30.137.9"
        - name: REDIS_PORT
          value: "30001"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-monitoring-service
spec:
  selector:
    app: redis-monitoring-app
  ports:
    - protocol: TCP
      name: redisapp
      port: 8000
      targetPort: 8000
      nodePort: 31111
  type: NodePort
